# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: coder-db-credentials
    namespace: coder
stringData:
    password: ENC[AES256_GCM,data:UyKMHm6pl+bwF/MICQI=,iv:DB7Q41g1B4Qa4Fn5x+JV4HFcCQHVqBjf2oYhifgXbLk=,tag:yTWXvV1m9Rw09nIK5G+o5g==,type:str]
    postgres-password: ENC[AES256_GCM,data:Sx2ZAMrw2xMga0JaVgA=,iv:Ah2dvvo+V2ok5K8DT5dAB1+PZ8hKN8QmgsDQNco9dTQ=,tag:jxTAlcaLeJ+GeKuj3hdxyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ejFFSnJBMzkyYVNtUVBF
            dWt4VTMrN1l3VnRWRFhyYjBrWk1XTTNmRDBRClowSVVwaXY1bnFOSjA0T1ZSOEZM
            bW4va0xKNzVMRG9QdXhxQW1oajJaRk0KLS0tIHRDeUM1RmU5aWdWcTRwQXF0R3dh
            dHRITE9DdUt5NjRkaEdOcStudlo2aG8KBfgaIvLByCCLIht1dH95y0UOLZKKwWFs
            DJViJOK+koa8OK0oiuY5Bnw0tIVfsw4ywK2QgiMVYR5ni+y19TBMtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-15T23:51:18Z"
    mac: ENC[AES256_GCM,data:URLVhiRRMFeLx/1+L599Mx8NF+jdASHDpjrGZkFJVIzk4GzcGruvai1+bWH6gz0uXrzCSK4eMzvxmHcHMiCBbMOLrYmm5hZnHKqga/Wrj3y9EIh3AA1gGDPAtJrB0H/Wbx1SWQ5v6bHn83gPspoYCK4heF/OuFUUUTMpm2Xq40w=,iv:Y00db/xFR7IpOr4EkxwWz6IEJkcpddEiEq9N8XvZSXw=,tag:2UBleO1Lt5OD5Au+1cw1Ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
