---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chatwoot-db
  namespace: chatwoot
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 12.10.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      postgresql:
        auth:
          username: chatwoot
          database: chatwoot
          existingSecret: db-secrets
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 20Gi
