---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aitbase-admin
  namespace: aitbase-admin
spec:
  interval: 15m
  chart:
    spec:
      chart: aitbase-admin
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: imtoanle
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                    - home-k3s-worker-7
    env:

    image:
      repository: aitbase/aitbase-admin-server
      tag: v1.0.4
    ingress:
      main:
        enabled: false
    # securityContext:
    #   runAsGroup: 1000
    #   runAsUser: 1000
    persistence:
      config:
        enabled: true
        type: "configMap"
        name: "backend-config"
        mountPath: "/app/config.yaml"
        subPath: "config.yaml"
      uploads:
        enabled: true
        mountPath: /app/uploads
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
