# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:8JXlfr3tdVZ8utN6aePaKBF2,iv:+bV80YNCcCVwyf3+tjXQQfYRue0FNzuuX0gQWmDNtGA=,tag:pAjqGfQRXOW8Xf3a+NtZYQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:ZmntFIFzduRCiJ+zNZPMdZK5ObdQnfwamv49/+ZoqZ6fr1Lhrw==,iv:2Ipd6hHr2/epRiCvTOLTNDyrEeVF7eS3piM1FuOLraM=,tag:YJXPRfvvpYlvqjLLZbHyZg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:+xWbn7UrqVTnxyR+EechSe50,iv:+Q+OFnE14Uc1tqP7VMYM5EM0M9xA6LWH4c81x/s/dKA=,tag:52StxnOyaFXWkr6gy3BmzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMCs5Q0VQTFVVVll0UTMv
            MzdpSWhkVkVCdmR1RFkvT1p2UTVJNXB1ODJNClZpTWJRcWZzY0lzb0RIVnNxUHl3
            SWF1VDV1bUhxWmp1MFo1QUZIWmdWbjAKLS0tIHd1RHhWaWVoKzBTY3F0ODBEbHpN
            WCtxSTVkeDZ4ZHVicXR0NDEycWJGaDQKPFNciZnoCEwjVWfeKub6aAq12gsgsHko
            0IfazvNxUBlP8AX2/fulttbDkHfV3+MW0GaCEDvGh+5r4W2Ld/CemA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T04:34:58Z"
    mac: ENC[AES256_GCM,data:WkfJnL2f6Ft39wWbwdDf+xDnMRwEW6bpyt7r36oYDr0TOK1QAYjR+dS4LlD6C9zjWOjoiv4PJLVCUMPJKGq/1ks1ZRLEYP2TZwONVovScfJ9ZLsUTiXqvJG/3inEsDPFcXEc2OkPNH3Mi04YhFxMfChtW/3z2d6aTQGY1ML7pZU=,iv:grCTJbcoi9GKiq6oQDtHpIBDTuhf92LThaZ3y73RNpw=,tag:OGhmNHQjy1T4xi5Dt0TJ4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
