# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:eIet5qomNmyCBFrD8mCndPd/,iv:Y1vPsux+8dK9pmAUiHzg3cZ0Zzd/lw67aEQmrY2VCK0=,tag:Et5XwWn2Xesil2nIJs7T3Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:2+75PG3hZeabIs+jzFEm+SbEuCW0g9ZcvblClibJFVEjkSHKRw==,iv:fyEUYrZwijYjnBXpYFt5yRAYQmhi6OyymZTjEYtnmpI=,tag:U7JfqijjOq57bkclv8wcRA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:CSCWvQJ6n2zpqhCfr9Sa2TUq,iv:QGqWJBplNIfB2dmi5LB90MRVb2CtnNL6IboJm+40Ke0=,tag:bsPQHKMvOsvbzm4CsuABZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UCt1QWhSRDVWUkwzQkpw
            Q3dXMzRwZXhxZFB3VXRtUnlXYXFGY2dYR0RnCmRoYTFTcWZhY2IzQUd0cVZ2M2JI
            RWxLWUlpUHBCbmhBQ05zWFhUcTA5L0UKLS0tIERLdTEwRHFPdFJmYlhBMk5tK1Bq
            OXlvbzRTRUJPZVY1SlpwbENydWUvYkUKAdb5AGM1LvzoWgA3CP73FXYp63e9bt7R
            aqjVvW59FqNeqaQiPe9OZUazFYh1k+8poUncTXVoWbu5iZyzPsk42w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T04:05:16Z"
    mac: ENC[AES256_GCM,data:BdOAw2EKagU96sL8GI6/35DSmUW9ER8oojGLTzPD6zPbchjXV8vHYeHTECLrTMqJEqXRCRmMe4/YlS5ffHJXnV3vHa3PViTjuwLpC8lZ1d/ganuPPgTUcIdkA4o7F0KfrhE1++2VTN7XD28Sr3LfXSAgyK1l6D+2yMeLxBK18go=,iv:ei3vTG7+55x+MbgjEWxFeXn0DPTjRLHjFeMqzhyym/I=,tag:cRwuKiTLP0+RIK5SDLoqrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
