---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prefect-worker
  namespace: prefecthq
spec:
  interval: 15m
  chart:
    spec:
      chart: prefect-worker
      version: 2023.9.29
      sourceRef:
        kind: HelmRepository
        name: prefecthq
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    worker:
      apiConfig: server
      serverApiConfig:
        apiUrl: http://prefect-server.prefecthq.svc.cluster.local:4200/api
        uiUrl: https://prefect.aitbase.com
