# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
stringData:
    encryption_key: ENC[AES256_GCM,data:WxrCvp5TUDqXJlSvxDliHejlzhp7DSy9,iv:eVZDsbRh5GL5ISXbS+qIXh1vA9ehaVIFvXcMBGh3L6o=,tag:EXFFiUvyn1Pj0sw/FsUkBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ejFFSnJBMzkyYVNtUVBF
            dWt4VTMrN1l3VnRWRFhyYjBrWk1XTTNmRDBRClowSVVwaXY1bnFOSjA0T1ZSOEZM
            bW4va0xKNzVMRG9QdXhxQW1oajJaRk0KLS0tIHRDeUM1RmU5aWdWcTRwQXF0R3dh
            dHRITE9DdUt5NjRkaEdOcStudlo2aG8KBfgaIvLByCCLIht1dH95y0UOLZKKwWFs
            DJViJOK+koa8OK0oiuY5Bnw0tIVfsw4ywK2QgiMVYR5ni+y19TBMtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T08:18:02Z"
    mac: ENC[AES256_GCM,data:I/h2fo2CEzkmQ1FBK1+g5NkzYdVC2+Iz49iF82huNvIpB2I5EsCXzI56ghej7ygwVorZ2vM3PJSLoU/oCFjqdjdAjrJU56ABwkW4RNO+mAgjwiQ4joeAY7O2Cok/roIx6QpXGBkyMSR1w504D9kV2igAjQr/mXm0nozuQ/y2kJM=,iv:LvlLdbrmX4B1ur6lhW/2pWU8rrsMOeXiPfXc+n4k+c4=,tag:qdxLMIz5/tHQwH8dNKwjAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
