# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: db-secrets
    namespace: prefecthq
stringData:
    password: ENC[AES256_GCM,data:JTfLqonTT+2t3csIztCm2w==,iv:0K6jkjiTzdwXrJt5rHgjRnPWBOU1BOJD/4Y7g3q2hXA=,tag:593aB+ADfZttEKGy/pk1Vw==,type:str]
    replication-password: ENC[AES256_GCM,data:xE1a2LtwZqIPNqp8FjHvng==,iv:20cYR2O6Fu6dsTIjTCr1ldyRCE7/nT3FbMMEa4QiTGU=,tag:1liuJc/kH5dwmakyvHWIPg==,type:str]
    postgres-password: ENC[AES256_GCM,data:pK/98si1yo0fJ6bIR/l8Rg==,iv:iU4Kii64csjU2CHHYgsRdiJsvU/m5wne5wYCUbKzmwU=,tag:Zt3BUh/ARvOobCwW2t+FlA==,type:str]
    connection-string: ENC[AES256_GCM,data:6KUC4cnPA6Mjubt//u7Aes9vBhMys+sfxvv8sYanplcVs+kr2gmxomVidS4xOIxwVlnYD1awgFw0qc0Uzvw1AKGmugOkYz8Pfvxbd5BpWPbkZ0zJim56Phu8muNakOH/rJ6zHxGMyAF9VTfcFoqaeSJrHQk=,iv:MWaURmEEfpOQbhAn/fKxSno6UbI9wxEibs/P+t5FOGM=,tag:o8PW+yVsx2ncuf/ZNuXRDg==,type:str]
    prefect-api-key: ENC[AES256_GCM,data:AXIOetP8semWdFFtqe1k6r8JFu/YTpSlvemllbCzm2apyOG6HbVfGg==,iv:r35JxPg9Hzr6/6toUhIOfvhTdnpdEMhr2oNZIUgwqas=,tag:IfyL9b9r8/bwKW8wFDLLvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ejFFSnJBMzkyYVNtUVBF
            dWt4VTMrN1l3VnRWRFhyYjBrWk1XTTNmRDBRClowSVVwaXY1bnFOSjA0T1ZSOEZM
            bW4va0xKNzVMRG9QdXhxQW1oajJaRk0KLS0tIHRDeUM1RmU5aWdWcTRwQXF0R3dh
            dHRITE9DdUt5NjRkaEdOcStudlo2aG8KBfgaIvLByCCLIht1dH95y0UOLZKKwWFs
            DJViJOK+koa8OK0oiuY5Bnw0tIVfsw4ywK2QgiMVYR5ni+y19TBMtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-06T08:25:22Z"
    mac: ENC[AES256_GCM,data:cetAL/78YRoA2p6uTdnHEeqT51+Nt9KWb8670ZeTGVcrkV+fLBQ80Q9VfqEgvm7aTf46ON/s+ygUhPlcKsDQrS6gRBN8AqyUpJwyeERb5jieKwc5NFeguJUBJuD52hDl4j6L/9XH2JwTAotYOFLF1+4fRA/basZo6lpXd9+CK0E=,iv:rZ0OnT4rlR9/Sq/rE9/dc35XDGsciL/y02dTVwGtkN0=,tag:EANZzXn8mADN0WCuHn24DQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
