# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:fCMV2Ff2W8ETVRmyQxLABQzH4ypf8ZANBocVT8CK/kfFff8dvg==,iv:FrtIjR1DVjWz2oeejv6sgx/xLXOj/TS4rHfvNiOafQU=,tag:P4rV35CAEJ/unIcSBEUzpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNHpkd2JBOC9XL0xlV1VZ
            UWhNYlBvU3ZSOGpVS29ZTGZkSHI1R1pvaVVrCmhQNlFaVDl5UmFtd2M1bjVXZ3Bo
            V09VKzFtMlZmdjdFcEVuRVgxMDhZT1UKLS0tIHg5M0lrZzhpN2JNbTNlRHFSdlNR
            NW5YQThBbFM1K1dUOU02djVKUmpQbkEKxJ77C31PpmK/fOVQM213jNBrTmUpf3ia
            2PL6Q0R6hcxbAdy8qJD18Puvo3C72+AVD423GWI7HTEv3eQ37eEVNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-22T07:01:56Z"
    mac: ENC[AES256_GCM,data:d7cF2pPlC6eKvCXxQj2BRPeKRGC2isuqnZYWHTZX1pLmNRnFNlwHXNzsulqct2dCVTp+mhW9USQO85B3u4Lxwevaajk8MdTdFqLAfz9U6W3vinwzdN9Xmbjdrka7h5tGYccLBxKS2trwBixPW1/lfqflaJdjDVS58tek1lhghjA=,iv:WAnBd2W+yNhoCSobL9n+tqnTXsyE4iuAQ5uvRwXHemk=,tag:Ds9BaQtTGRs8p6DPjao1OQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
