---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aiom-db
  namespace: aiom
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 12.5.9
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    global:
      postgresql:
        auth:
          username: aiom
          database: aiom
          existingSecret: db-secrets
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 20Gi
