# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:rQjsZqT8DwZuUBmwzA==,iv:g0UVxhovnszmx/JG6/xeMoWdEg0+5CARSYBpex0/sRI=,tag:5OPQC4tcojBI/crJxBNGkA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:0fhC3QxgSEgmowEgvDLTT3X7,iv:8MpkcbNcvEj9FqHhNixikqKUGUYcpbHNeQJw/JFP0Ks=,tag:lqgwvsEjtEslwKHxkHJKqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNEVFS2NoTTJscEN0ZzVQ
            U3VxOUNrUzBXSHRNeUdraUpKYUx2UFp4QkRBCnhrNnVMT3dPU1F0cHpzYnNob05Y
            OUFWT2k5Q0NBWDhZQWJTV0Zsb1ZqZlkKLS0tIDBiZ1ozNGdRU0xyUXNrelliZUVx
            Yys4elByN3AvTnBiLzJBN1ZXNEJ3NkkKxwred49vnwpy5+SM9T4meR351TO0ob7R
            MUur6T2CxCL7+urQ7Zf/TJ2gazLb8C5Dedv41kjWAuuG7WmRmTZAPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T04:34:58Z"
    mac: ENC[AES256_GCM,data:JoRCEOdgzLxbheHD/wxZvnRw1zkqKrAnFrl5XYjXoe8Pd0HNw9Rj54IeeAotXh7AEVZMgP0w3PmPwv3EYdOG1blnJwDhsBvmLRMB3N/0NmVQ+mImRJ4KT4hLDDThZB9JpvPZl+F0O99VrCQY4DxjRZar6NlX41NOyApKO00YcXw=,iv:ZPK3r5d1GQoY2JSpqEshwY0bIf9xCLMLS0bJRy7di2A=,tag:NWwiw+VO3/xKQ1NxPloY/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
