---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Asia/Ho_Chi_Minh
  METALLB_LB_RANGE: 10.0.100.230-10.0.100.250
  METALLB_K8S_GATEWAY_ADDR: 10.0.100.230
  METALLB_INGRESS_ADDR: 10.0.100.231
