# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:j3dn+1sOtEzOJUZJlg==,iv:k8aVcUAifFa/7mR5JZ1UfmTjMw2ExgJggdW4QhWvJ6o=,tag:IiZhWyFYQF8T65aXPEk3ew==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:I/OSPLoym8siOXFou08nUeJD,iv:ydPXFNn25wpZhNTWkjuGSmelfmbAcncTJpsAnkmSGSw=,tag:0hwORfr1ukfTVy3Lum/L4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aElMRTdxSlZZRm95ZEFG
            WkJGbGcwNi9YU29IVmhrN3U0SHRyWTdSOFY0Clo5THRlYkFwaHVIbEtreUI3dXlw
            Q2tvaFVFTlhvTGMvR2FtcStUYVdwV1kKLS0tIDBNY0dnSGtLVDNPcTZ2WFlMdVVl
            RjVJVzFFMzlwR3lXRnlpYXJoZnhOancKXuUzwfra+2ghEXkg8v3zE3UeGTiiO9fR
            l5F+qVlcfCIVCRlNduLNWHVZVEmj1/DSn0mwN7/P7FfR1sQ7YO7nCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T06:45:52Z"
    mac: ENC[AES256_GCM,data:aoHRvN7bVN2+qDJYWoZEEWn/R5YzahVMKiZSBXsAbio+pOQD2F945Fra76s9BhgKK8knynQwhYUzcM1WzLx+GahLS2wgpIaushN4j60z8DpyQR6XwrjB1JYxWgodVLh9msv4tH00HUuzmqbVwhVeXzIj3rAq1/kHpEj2M/BiLPs=,iv:ZNbUwRB2NumY1ndKqaU8HfaFkUOxl5TMMFR6Q3itZhs=,tag:qivSZWc/DnA3/CDYeth9xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
