# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:47yHJGRMTDf4KFxSpw==,iv:J+2UHW6fmsoabpZrgkKDf07BOPRpzPDNf05EUEIOjlE=,tag:cJSprClCnNqZSka5mh6uhw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:VW/YloEzK3kjf+pwhNq07WpM,iv:DsOtBaNJOAZFgqFJnt1oOHEMjlB0vxgu7yZS2VJNasU=,tag:tVA2+3/B7do8whMFfQwPSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eUczdWhRZzhRVXYySGZD
            STNMdmxHSmxCM2VOWDJsSWVhbFlyNUtxNlFrCkJ6dmNGc3hPdG4zN3hJSStpQ0lW
            U2V5UWgvMmVSYXZNRmRCcER6dUNsL1EKLS0tIDJIL3hYOE5kTDcrQ0lsY3FucXZU
            ekRVMlluK2NxSjdudSt2OWZxb3JPSjAKkxA9lcKwNMQlIhwO51J3DQ6YcCHKVbVE
            Pcr2JpX0Tr0JMMii/ijMHq4rsTRuYV9cZ2GdmZNxg6urIPU/rqnoVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T03:28:41Z"
    mac: ENC[AES256_GCM,data:MZNG8WEkvrhNcoY5PDnosaDuyoyhQBvKU6dZuYjh1/DVJpz5wX8MlhVaLpJd72WxN6kGxN2c/Kc8zw4/XaYRYPRsYYFbwFEEbqeCgeDqpO4+AVTQ+Ves3a1AUVqiOvn6sR65yelUV6Zo/kNue3M8m68XgKNP7ecIX2a2ubjO3o0=,iv:UNVHtr5l3MIm+YUuuM0Hryl18abEP5mQMP7bBOePnrk=,tag:0Zw9wd1OiRN2qI6n5Csktw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
