# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:dmfqg4RMrYd3gB9qUw==,iv:b903vBlYaPjmo4f9H7VqD+EZhboV3UkefLPKQ1FNYhM=,tag:dTdxmbE6UBNYkcp7Pw0NeQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+nQXxIuqRdt/5U1pnc3AuEXh,iv:moXwhkrd/a2udGXz1b5idVV9R20p3C2nwntZ2iEc1vs=,tag:12cenMEyoPqgUnZzzGRY0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dEhMcjZ0azNaNnpxSEs2
            NnlESGcwSklkSFVBajd2aEthSHpXTGxoNW5nCkVoUjVOZlRYczF2TENGdmVJUTdz
            RGJqWkh1aGNlaDJDUzdiQURYVGRUTEUKLS0tIFdjdlJZK0xwa29vNXNoZWFwVDk5
            VUxWdUhEZ29nU1NuQ1BXd29mUVJvR0kKyzi1Lbg0/Rf1CjMqEfhuxXEwtLKDX6iG
            WMh2XiOHcYZJv2I9fIYGp3++N5sunMWPq6YqfMOB64LRNEsa1xxyDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-22T04:01:52Z"
    mac: ENC[AES256_GCM,data:2CU0K1tU62kXNJCInKDdm4uvqSIKmOiv4xUioejMyW10zh/7ZAiBOg0vcBPsIJs/8L7s21Wty/4XssBfL72nMw/RxfvXaIn9bPxdXHd83E3fTmiMPoIlkrt1DFua63UrEpHkJQWH4sRwA8tM5o+kn4ifbYCNuNCGjeFXIQC/x1o=,iv:OCIXTK5ElShqLGusxV6s0O4D8NEKj1GRqUV0OCrYTtM=,tag:2L+diDE1fmhPkjjZ98uaiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
