---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: comabase-web
  namespace: comabase
spec:
  interval: 15m
  chart:
    spec:
      chart: comabase
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: imtoanle
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    env:

    image:
      repository: aitbase/comabase-web
      tag: v1.2.3
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns/is-public: "true"
        hosts:
          - host: &host "vietwings.aitbase.com"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "vietwings-comabase-web-tls"
    persistence:
      config:
        enabled: true
        type: "configMap"
        name: "web-config"
        mountPath: "/etc/nginx/conf.d/my.conf"
        subPath: "nginx-my.conf"
    # securityContext:
    #   runAsGroup: 1000
    #   runAsUser: 1000
