---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app frigate
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: frigate
      version: 8.2.2
      sourceRef:
        kind: HelmRepository
        name: imtoanle
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          # cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "10.0.100.231"
          # external-dns/is-public: "true"
        hosts:
          - host: &host "frigate.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "frigate-tls"
    configmap:
      config:
        enabled: true
        data:
          config.yml: |
            mqtt:
              host: "mosquitto.default.svc.cluster.local"
              port: 1883
            record:
              enabled: true
              retain:
                days: 7
              events:
                retain:
                  default: 14
            snapshots:
              enabled: True
              timestamp: False
              bounding_box: True
              crop: False
            cameras:
              # Define at least one camera
              door:
                ffmpeg:
                  inputs:
                    - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.85:554/cam/realmonitor?channel=1&subtype=1
                      roles:
                        - detect
                    - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.85:554/cam/realmonitor?channel=1&subtype=0
                      roles:
                        - rtmp
                        - record
                detect:
                  height: 480
                  width: 704
                  fps: 5
                objects:
                  track:
                    - person
                  filters:
                    person:
                      min_area: 1500
                      max_area: 100000
                      threshold: 0.75
                      min_score: 0.60
                motion:
                  mask:
                    - 513,36,680,39,683,21,518,21
              livingroom:
                ffmpeg:
                  inputs:
                    - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.83:554/cam/realmonitor?channel=1&subtype=1
                      roles:
                        - detect
                    - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.83:554/cam/realmonitor?channel=1&subtype=0
                      roles:
                        - rtmp
                        - record
                detect:
                  height: 480
                  width: 704
                  fps: 5
                objects:
                  track:
                    - person
                  filters:
                    person:
                      min_area: 1500
                      max_area: 100000
                      threshold: 0.75
                      min_score: 0.60
                motion:
                  mask:
                    - 513,36,680,39,683,21,518,21
            detectors:
              coral:
                type: edgetpu
                device: pci
    env:
      - name: FRIGATE_RTSP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: frigate-camera-credentials
            key: camera-password
      - name: TZ
        value: Asia/Ho_Chi_Minh
    image:
      pullPolicy: "IfNotPresent"
      repository: "blakeblackshear/frigate"
      tag: stable-amd64
    persistence:
      data:
        enabled: true
        mountPath: /data
        accessMode: ReadWriteOnce
        storageClass: longhorn
        size: 20Gi
      pci:
        enabled: true
        type: hostPath
        hostPath: /dev/apex_0
        mountPath: /dev/apex_0
      media:
        enabled: true
        accessMode: ReadWriteOnce
        size: 6000Gi
        storageClass: camera-nfs
        mountPath: /media
        subPath: Videos
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        # mountPath: /dev/shm
        mountPath: /tmp/cache
    securityContext:
      privileged: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - "home-k3s-worker-7"
