---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app frigate
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: imtoanle
      version: 8.2.2
      sourceRef:
        kind: HelmRepository
        name: frigate
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    config: |
      mqtt:
        host: "10.0.100.105"
        port: 31883
      cameras:
        # Define at least one camera
        door:
          ffmpeg:
            inputs:
              - path: rtsp://admin:CoolBoy2022cr@192.168.1.85:554
                roles:
                  - detect
                  - rtmp
          detect:
            width: 2592
            height: 1944
    env:
      FRIGATE_RTSP_PASSWORD: "CoolBoy2022cr"
      TZ: Asia/Ho_Chi_Minh
    image:
      pullPolicy: "IfNotPresent"
      repository: "blakeblackshear/frigate"
      tag: stable-amd64
    persistence:
      data:
        enabled: true
        mountPath: /data
        accessMode: ReadWriteOnce
        storageClass: longhorn
        size: 15Gi
      usb:
        enabled: true
        mountPath: /dev/apex_0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - "home-k3s-worker-7"
