---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n-db
  namespace: n8n
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 12.1.9
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      storageClass: longhorn
      postgresql:
        auth:
          username: n8n
          database: n8n
          existingSecret: n8n-db-credentials
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi
