---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: camera-nfs
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.17
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    replicaCount: 1
    storageClass:
      name: camera-nfs
      provisionerName: homelab/camera-nfs
      # pathPattern: "${.PVC.namespace}/${.PVC.annotations.nfs.io/storage-path}"
    nfs:
      server: 10.0.100.156
      path: /mnt/camera
      mountOptions:
        - vers=4
