---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - echo-server
  - frigate
  - hajimari
  - home-assistant
  - mosquitto
  - n8n
  - photoprism
  - qbittorrent
  - trilium-notes
