kind: Secret
ansible_user: ENC[AES256_GCM,data:KIweGg==,iv:HsmNTt7pK97Ph8VDPyiXisMl7MzuyX/5NYWljyBgBlQ=,tag:xsqG3hPjj0sCXeIq6K3K8g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:LmG81bLN/Z4Dsl/LPb+f9A==,iv:qtfAEfUbazm17GNiYcEZWF4IpNy0K8oI3XA7LjbzMrA=,tag:xKMOZDgLuMHKYYAxrBy04Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSHJtZUtnYkdpN0VoWGs4
            WWczQ1M2b2FKdXpjV1hZU2hpUFRqVEczYUUwCjNUbWNUai9Pd0h4NVY3MHdnYnhM
            Y1ZmbGRBZkVUampST04rZU1qTzJSRjQKLS0tIHBxVzZTamYrVUtZZU4vMlhlQXJ5
            ZXBOdno3NzVuUHBKSk55MjlPY0FBRTgKi5VqHe8/xwoHLePlDzyxKZrhF00H9Zmj
            ndRyoMJKIN4emadp8Yk1fFJYkA2IFU3qzoPDbq4TvgawwOA5JnJpgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T04:05:16Z"
    mac: ENC[AES256_GCM,data:fpy+auH9QSIWsj81foHLaGtLHrEbEMmDhVeN81ngitkfVRRsxTE4jP0s8lrQdqE6Ed+S6rMvowFJTjaqWqtdrNMXkwRYcNKaqoa8Y0sxi2ZvBEK/PlRhfS+rDMr72/HBN/XU0TfPxBkyrVpEeW4qDXf8qnf2dHCluOqpVAK822c=,iv:DcB1wTJimpcfpFXmanSZ7REK3H4E0haxN0q6a5w2mgs=,tag:VSZHl6IAYMctbK+JxSFHDg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
