kind: Secret
ansible_user: ENC[AES256_GCM,data:CingmA==,iv:srizqg8UznIPiwTT6+Zru2Pw4ZYT4vShWTw9YKjwCf0=,tag:nZyo7xN6JH73CAKvzLEzZg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:zueXJvifOL54HdKj452t8Q==,iv:u7Iq4A58VEexFbPxidj3yjNcag7z8w0fW4CxgysmJLo=,tag:rXBYrkbYkrkE5g/YG8mc0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMTNzcmNuRjJmVHpzZ21W
            UmxRNEVMS1JOMTg0cVZFaFB6OGRMTUJoK2pvCjkvaHdLUzZITkxvWndSZ1VaWE15
            NEpPaDFyNnlWYkp2OWF5djlXd1cwWEkKLS0tIDRIR3FVRWxlcFV0emkzNHFiSE9S
            QjhuQ1lRRCttUDUxVWhOYk5heEQ1SGcKpAxOTjErjTJArQRq947w50LNcUHOLuP2
            La4IpTcvbMTa2j2L5Emgs6fqTBLs/Dn4oD7lHPfem7qFIiQTwYY8VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T03:28:41Z"
    mac: ENC[AES256_GCM,data:shPa83Jqf7Izi64c3AfPidyayGLw/c09Yn8A4/R5XDjt/ckO3yKBNbLwbxraD2XVrtNA+aBY9FwFbfY4lUHqu1ZD1L+Fy0NkcuAU6YdcZG1//ZLGdffw/9QnZ3PVjVk0gfHYvj1elMnELypnmk/BIv1zxFsbHFCCsqSf09QZzKk=,iv:1TVnNuPGnU8AksORTo+d3Tre0dDHLONXYf5wLmb/9LE=,tag:gdSiPIkLEbZYcxyqtUcucg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
