kind: Secret
ansible_user: ENC[AES256_GCM,data:198W8A==,iv:y2TnY0gZmjrclRoW+0Ty39ru3J86eRVzft9doixkDes=,tag:HKazsZwMd3dzNu5v8NHAiQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Ou20eaRFtjxBf9XnlKHc9g==,iv:6I86iuEiZOAyJyWi7f7VqdCnJaE9fGUF6bbWNKQj7kY=,tag:5WcHe5QmvYJIPCbqIHmuCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eTREL2VtcXNhc1h2bHpr
            MGJweVY3WlJVMXJpN2dOeVVzUHlaVHlSVEZjCklXVkozTlhONytFY1FwakNOWkdK
            ZUtiZWVpOGh4c0w4Zi90VXhmQTB1U0UKLS0tIExKNU1USkNleTUxSnJNN21IMks2
            WkFTTW9paHBKQnloOGZWODI2M2xaa00K7U3bpjwkGdtG7gyFFz5TUt1lDkUxTIUU
            mqoyDFWNqx5BvhcaWryqNt5E/ZrIe913m9eOMub1kisoouPMpiuFOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T08:12:06Z"
    mac: ENC[AES256_GCM,data:rDkHQWZL0yBXold/zyQceKXnKcwdnLSfdV59uGgwjuOzRNozTSxdq1v+1aBhu2M3r66lkYNt3JdX0GfZEFzhqIyAiU+7oxaUwbfGTzBc/KmgXIrlDxvEmRFXDHAnLUX1GDfYXkqTAcGvxHI4MGkZQqc5/PsfBM2DCkz0zc8Iu7w=,iv:MisZGEXIbwaq7mDa9kDqxqqZlbgoPcJpDfaJBS0e7rA=,tag:ckXAy/4+o3EcnrOud7YNzA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
