kind: Secret
ansible_user: ENC[AES256_GCM,data:GHev1g==,iv:wGIwI+4dB4B9J5ZaRk6BQ2tojU9egZTfTKqKuj8xgnA=,tag:4QN6Oqo9qAlqhK7erfQmcg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:EpwpsX02tVDipWqbnIJbCQ==,iv:2GgD5UjIiAEGVrtkKC94FAaOocq81KyU+IZpvkoyc1Q=,tag:VAX36qvV22q/HJpdrx4axw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbkN1MEUrMXQ1dFFWZU5G
            OUxYYzlYOS9uWjFDOWlsVmUzRjRpSE5VTkZnCnE5Nit1SCtIaGJsTzY4QnF3cEsv
            U3VmVVBIM1ZEd3Evdm9VNEx6clRCR0UKLS0tIGpDWVBPSkZnVSt3dndLL3JkN21Z
            TTJ5YXBPeWxZeStLYmpGTHFMS0ZFT0kK4P5tPVq1jdwvRuBKPgTk+8bxtPgo9J4v
            9LHzjFDq+q6gubooWMLKdGbmVm+fevxCLHgdca2Wy+7jDNqU63LuFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T03:28:41Z"
    mac: ENC[AES256_GCM,data:Zuj2OCYmt+zEtivy1PjL+nt6O9uDAq/FrSoOOHe6j+qYWa2E0D+yHvuDbjKeJoRbOeDQCKlB7Bo5ZBqmhalvpg9BPFx0M355bjkgzW5bNNq0b3AOtBxuG/I4ssXHeiQuDszl74330jw8KKQqN3IL03TWnb6GN32fsL0/ZJd6K2w=,iv:+j8x4v8nHElj+AIMUAjbseOw5LNBNKunpdsNka9rRKY=,tag:NiknNeD+auB0YMo0z5smKQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
