kind: Secret
ansible_user: ENC[AES256_GCM,data:pd58ZQ==,iv:q+PjzV1S+SaUJ1Mn0gzNk0w2P1I5LVZH2nleoIXbG1Q=,tag:c2DF+sQmuP6IZJEMXO/MMA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:0ptjtbAA75d9bdMcN6oPHA==,iv:uWzoOvQDtukUsWup+GHBBWRWk6gH40ndDkEDYFjs7dM=,tag:DlsPATZsZih+wS97tndpdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q1BEMlBUNFVHc1ZzRWRO
            a3krNVNBUHhxNXdLUC9GakxUVTA1cGpvdWtzCmRHTTE2bkVJbHozVXp0Zm1XZGdr
            cW1jeHJTNnRkRVNpR3VqUHVGTzhkbzAKLS0tIEQ2SzFlZ0syMDZZMnVvTWJJU3Z2
            RHVVMlhjMFVOazU4cnByc2cvNzcvZFUKaVdhWb7KNoUA/8akAnmhA761cg6yDxZ6
            WKt24uwldWCoh92dHhQTkWU6u/3MrV5b2HAH7sfunm9ptjvyyzvtNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T03:28:41Z"
    mac: ENC[AES256_GCM,data:Nl/EWVX8sICD9rsPvEWt8y/NFNyvMwIfkqH9Scp/v8BWQQ31DRWuhizOcAjRXv2vSvET7LLtyc2gwfTEo0gyI5HYBw6sADMFeHQsJeU7WSxW0HGyzZqLk9YAbD1KMAvhgCW3t8FF1QWJVs8Gzw4XuVSHXPiVEt25KywA83w5Hmw=,iv:jMAXwaTjXugZM4Xm68xZALqmnvf/Nfaaj/uyvSaCD8I=,tag:y8kLvL+ZM7NcZD0hnp8ftQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
