kind: Secret
ansible_user: ENC[AES256_GCM,data:gnqOlQ==,iv:cyU4/2hAxxtcPZRz+hlifexh1XF9z5DDl7tTlOhYKsw=,tag:VsS6u7VpAQM3HbPNkoiSbQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:c/CkfARdZyRQThDidzCc3g==,iv:E6sp0CiyIhPIvtMXvDL6MN223Nbb7PKzJD/bJfaWtrE=,tag:JY5epWy4gg3z84Rh4X2aLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdXRrTFlJRUcrazZUNUFm
            Szh4em05ek1UV3ZPY0E4anRJTk51NWdWamowClU4VGFIMzB3RS84R01BYnBmTzdl
            U0wvTlpIaDRJNkVtS0E4cUw3VHZWa0UKLS0tIGJHRjFDVi9lUnRBcExISzZqMWdi
            eVRIZkE1SGZQb0JBamN2Q3Npd0VtaDQKro+B0NG2wqt7Tcz+QlFXH9+OmPdOu55z
            f0tIZaDSznkecMBN5KVX6LVuGIKliM+DkfX6dLMx37PtWex1q6xlPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T06:45:53Z"
    mac: ENC[AES256_GCM,data:YnTI57rzQmTxTEUhzpc0zgrQ0WZG/5pJ6xgXOXGULRluaJTtwh0KH1FbDOJhsFuZ9S+rxFusk9RelnwDp5bb5wE98GL4YUIYoAG9ZB38vNvWMcyH9nl6TzO4kZ7iQwhZzRYENwuVCXKFm8RQCNDYe6zIJ385/id6hd3dDqWpBdE=,iv:ZQM15qYkvrpgCTYzIcNVLB2gSa+/JZcBgnpeNmGOJFE=,tag:Ya9mITkIW6Gj/x4prGOKVw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
