kind: Secret
ansible_user: ENC[AES256_GCM,data:CSK4WQ==,iv:TcBCmAex7LG6n74431vIYgb+qaPvf/NwCXF2UiIrjQs=,tag:1TBD3cLUQPeu1hsn8m4sjg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:hD5lmPAR/EP6VJ4DLtcnOw==,iv:zpaFBc4UFxwBca9u0xVdIZ8wiWBm5rnjt7QKyINjeQE=,tag:s1mU1qEql51Z6ItCHPspEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUCtyMG5OZUlOQnBwOFpG
            Sjc2ai9mbzZGcDUwSlBRWHJSRFNkcDhhSmtFCmlSWTgwMmxlcXArYjhKbzd2ZHhq
            dGEwdU91aTJQNkxSM1BkNjZ1VWVHZjQKLS0tIE42WnRtZFBRRkZJd2pSaFd4NFgz
            Wm9RdUdlckNIQWhEdEVBa283RmFqb2cKQ3G1E1/aTlt6dsJ2NsSGgrAfRZ5a2bE+
            7+VS2UARE/cTd8uGoMY6bzz4Cw1pnI+3msHwjFGDh0gG+hOLhBiBPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T03:28:41Z"
    mac: ENC[AES256_GCM,data:GkHyBLvlivwXpYhxypLz8h9UGQ+tvEczc72OArTOkmhS755451qrN2myjM8e587aAp8PKaVdgNpvkNR7RBX26S9llc+W23k/2QkCOxbGKZVDscD/4Xfrl8imXWFagdZZhIFDW0454eXO7STyORQplOrIoaemT34ibmk/dj1S8k0=,iv:DMYXSA8kJUrs2UmtC8jBZukmazitlaKKjb9MexKzT00=,tag:U95yKawkHaUQDQKu0ADMPA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
