kind: Secret
ansible_user: ENC[AES256_GCM,data:plvIwQ==,iv:Dqf50LUjRf3XJDFENuN7nYoZFShtaSnxrnEQqUnohk0=,tag:izujk3NfZFd80svwBnZinQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:wa90Z6nYHRYcNZVZbTjZ5g==,iv:dbr7btthYyd501J07flW18iZGOUIBpFDaymfHr+KPH0=,tag:58VsZJa0uw09XxDisFva5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUG9xVXMrY05aem9SV1Rj
            aEJmbFFtbEVrTTJQWFdIa1VsTk1IUkJlVkIwCnN3OHdCanI1QVY0MWtSWnpQOVRG
            aDZEVHNKRDRYSVJ0QTNKVW9QVU1CSkkKLS0tIFJlK0NoN2RQaDM3dW40TW5vZHcy
            SkN3NWdUam41K0VwTi9DdTFMa0M2RGsKjM3eRPzJMQjLKqLxaGYSAA84jLcGy8kd
            mYvXpxVhnZRLRdJdOBJdtxl/gtz8hBDUitjyxHQMMdSOhM3T9/mQew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T08:12:06Z"
    mac: ENC[AES256_GCM,data:ZRDxfHRxDtl3f4ERGFj8tZTd6Y6X5VjgE1GNBAPdH8S+gz7G5ovdEpue96xOGa9/bFF6+3rYotUw+YocypSRR2vvljDbZ68UGH4OtCsUP3BCYEtTumj0whvZ/wfxA8+tlKV+5mlu2z/fS1+UKaaEoGaLTOSkNdZ1xoyfffPOq4U=,iv:jenE47FxufUzgfhILbwenpvxOVqtg5bp/NGNQbNejdY=,tag:hM0nQVuf+abmFtqIuPQxmQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
