kind: Secret
ansible_user: ENC[AES256_GCM,data:MJWHfQ==,iv:Sz91pxvcuXRtG06gNGciXjyQ8e5GtlNEN8psJqQzuOk=,tag:EyyF07VTYSLXeKIQsMeVPg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:6rD+W7aCzDw5loPq2ex3KQ==,iv:apcc2CPi3qV8NhQtpFdbHu2F0Myef5Mew4Vl6UFx7Ok=,tag:aKSWOAlI3aSkPDJuzGUQmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUlIzU0lhd3BMRjBZOHQ3
            d25HZHdLSUFOdlR0WDUvMDZnUlJBK3pzZkM4ClBTZVB4Y0VMd1ZtdGxIOVo0NXFm
            cFN5QUxJZlJxczM1cEkvV3NXQm5kV2cKLS0tIDBNclh5M05MbHVMd2pxM2twRk1G
            ZVhyRHNEVlU3T2JOaVRmQjZpY3Fpa0UKTAqHERC3oxxL+ImGJk/hEpz3R6CvcbPn
            /T+dJDLOAEw1G6r1AqdFH6ajOYMtILW6Yyh65P/IoSx6rtLWHnTaeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-22T07:01:56Z"
    mac: ENC[AES256_GCM,data:/cr9IzzCC38K+OZig25TQD+rtgLjrZNBia+oSlY+N4bGRkYVRIXMx8qGS3z3khMsy2ADlPnutLkb+HwBlfXAR5mpw0JEQoSXLB4IhHZDznTmpfFZgJBBMmHDTLNSSrMlkC+RQ/wvTco3SrOM/GEXmq3IWitTTXhUZXp9y6SWgk0=,iv:Z+bUbfixxcsMb34hrb/e52znhDD4L4xKggLromZiaWA=,tag:/OPKnQLBGH9LpMVBvXCu+g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
