---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 15m
  chart:
    spec:
      chart: n8n
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: 8gears
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    extraEnv:
      - name: WEBHOOK_URL
        value: "https://n8n.${SECRET_DOMAIN}/"
      - name: DB_POSTGRESDB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: n8n-db-credentials
            key: password
    extraEnvSecrets:
      DB_POSTGRESDB_PASSWORD:
        name: n8n-db-credentials
        key: password
    config:
      executions:
        pruneData: "true" # prune executions by default
        pruneDataMaxAge: 3760
      database:
        type: "postgresdb"
        postgresdb:
          database: n8n
          host: n8n-db-postgresql.n8n.svc.cluster.local
          user: n8n
      generic:
        timezone: "Asia/Ho_Chi_Minh"
    secret:
      security:
        basicAuth:
          active: false
    persistence:
      enabled: true
      storageClass: longhorn
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
      hosts:
        - host: &host "n8n.${SECRET_DOMAIN}"
          paths: ['/']
      tls:
        - hosts:
            - *host
          secretName: "n8n-tls"
