---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: comabase
  namespace: comabase
spec:
  interval: 15m
  chart:
    spec:
      chart: comabase
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: imtoanle
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    env:

    image:
      repository: aitbase/comabase
      tag: 1.0.0
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns/is-public: "true"
        hosts:
          - host: &host "comabase-api.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "comabase-tls"
    persistence:
      config:
        enabled: true
        type: "configMap"
        name: "backend-config"
        mountPath: "/app/config.yaml"
        subPath: "config.yaml"
    # securityContext:
    #   runAsGroup: 1000
    #   runAsUser: 1000
