---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: comabase
  namespace: comabase
spec:
  interval: 15m
  chart:
    spec:
      chart: comabase
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: imtoanle
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    env:

    image:
      repository: aitbase/comabase-server
      tag: v1.2.8
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        type: "configMap"
        name: "backend-config"
        mountPath: "/app/config.yaml"
        subPath: "config.yaml"
      uploads:
        enabled: true
        mountPath: /app/uploads
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
    # securityContext:
    #   runAsGroup: 1000
    #   runAsUser: 1000
