---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aitbase-admin-redis
  namespace: aitbase-admin
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 17.7.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    auth:
      existingSecret: db-secrets
      existingSecretPasswordKey: redis-password
    master:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi
