---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netmaker
  namespace: netmaker
spec:
  interval: 15m
  chart:
    spec:
      chart: netmaker
      version: 0.3.3
      sourceRef:
        kind: HelmRepository
        name: netmaker
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    wireguard:
      kernel: true
    baseDomain: "${SECRET_DOMAIN}"
    dns:
      enabled: true
      clusterIP: '10.43.69.69'
      RWX:
        storageClassName: 'longhorn'
    RWXStorageClassName: 'longhorn'
    ingress:
      # -- attempts to configure ingress if true
      enabled: true
      className: 'nginx'
      tls:
        enabled: true
        issuerName: "letsencrypt-production"
      annotations:
        ui: {}
        rest: {}
        mq: {}
        base:
          # -- annotation to generate ACME certs if available
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        tls:
          # -- use acme cert if available
          kubernetes.io/tls-acme: "true"
        nginx:
          # -- Redirect http to https
          nginx.ingress.kubernetes.io/ssl-redirect: 'true'
          # -- destination addr for route
          nginx.ingress.kubernetes.io/rewrite-target: /
      hostPrefix:
        # -- ui route subdomain
        ui: 'nm-dashboard.'
        # -- api (REST) route subdomain
        rest: 'nm-api.'
        # -- mqtt route subdomain
        broker: 'nm-broker.'
