# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: db-secrets
    namespace: comabase
stringData:
    password: ENC[AES256_GCM,data:ykU1VGrFjVuhc2jm92M=,iv:XOnWWahJFiLaWkxn2jQZnCtzGLfdmUEY3cpGzbiKA40=,tag:uClc3Pj72LWgBsR9Mkf05Q==,type:str]
    replication-password: ENC[AES256_GCM,data:LIbgAdLB10h+HA9dJAA=,iv:UXPxkZ54HmJvoHjusb4LOB3wJZTzS/34oXri7+UtDoI=,tag:RraN9r9VQuOeBtQqiEsL6A==,type:str]
    postgres-password: ENC[AES256_GCM,data:w/X9paCJgNB1cZAgboA=,iv:QxC3L8skUJN758PrcHrjo+wDg3F6d8Nsw9mRf94NJRk=,tag:MJ2sZ7aNX0GReynA4p9vKA==,type:str]
    redis-password: ENC[AES256_GCM,data:6qqPakqzgxoD2YH7MsQ=,iv:Orojv6kzbJ/LIWm5QDLr23PrQZOL7aZ+WCde766omLE=,tag:i4l2V/rMZ4byfPKiI9KK3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ejFFSnJBMzkyYVNtUVBF
            dWt4VTMrN1l3VnRWRFhyYjBrWk1XTTNmRDBRClowSVVwaXY1bnFOSjA0T1ZSOEZM
            bW4va0xKNzVMRG9QdXhxQW1oajJaRk0KLS0tIHRDeUM1RmU5aWdWcTRwQXF0R3dh
            dHRITE9DdUt5NjRkaEdOcStudlo2aG8KBfgaIvLByCCLIht1dH95y0UOLZKKwWFs
            DJViJOK+koa8OK0oiuY5Bnw0tIVfsw4ywK2QgiMVYR5ni+y19TBMtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-29T08:35:07Z"
    mac: ENC[AES256_GCM,data:oOOxgd1gTFZm5xq6jznGcdZ6TkI0SdZ+n4huKo6SkatiUGk2HAwxh3m6vGjVTctn6v42iOk4+T2oNXCR81d7Zhm+paukwJGF2NZxeFP3kTCEDHUwIgo+qm+0uz4SGW+52hK8UevttdIQIKFUQEH+aJSGkVK+AaWAbJ/JhKVVrJk=,iv:oWg8Ho+mzkWuMP9RI2e20vAdBFYWg6pW7UDOGQHcfvQ=,tag:UdQxnYqrxYzqgxeAi/0qyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
