---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder-db
  namespace: coder
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 12.1.9
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    auth:
      username: coder
      password: "${USER_PASSWORD}"
      database: coder
    persistence:
      enabled: true
      storageClass: longhorn
      size: 20Gi
    env:
      - name: USER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: coder-db-credentials
            key: password
