# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: coder-db-credentials
    namespace: coder
stringData:
    password: ENC[AES256_GCM,data:UyKMHm6pl+bwF/MICQI=,iv:DB7Q41g1B4Qa4Fn5x+JV4HFcCQHVqBjf2oYhifgXbLk=,tag:yTWXvV1m9Rw09nIK5G+o5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ejFFSnJBMzkyYVNtUVBF
            dWt4VTMrN1l3VnRWRFhyYjBrWk1XTTNmRDBRClowSVVwaXY1bnFOSjA0T1ZSOEZM
            bW4va0xKNzVMRG9QdXhxQW1oajJaRk0KLS0tIHRDeUM1RmU5aWdWcTRwQXF0R3dh
            dHRITE9DdUt5NjRkaEdOcStudlo2aG8KBfgaIvLByCCLIht1dH95y0UOLZKKwWFs
            DJViJOK+koa8OK0oiuY5Bnw0tIVfsw4ywK2QgiMVYR5ni+y19TBMtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-15T16:29:07Z"
    mac: ENC[AES256_GCM,data:3ifoHqk9Hlcwx7P95ND71QC63ItvuHHRgW5vP9dCiEwYLAx9I+MkRgPf+X0nENxZdzswls0zXuDaMD2auIn33aLVO+YHypA9ALaFRHxu4mhR1+nYU9zaXHRruSpOCzOIewceJwNbur712oyVfvLS7Yfwrhx7gMt+DWUAKW0jheU=,iv:t1+jlIuphSL3hMfE4wu7ZqYKKfNdqgfoNhk3cbdX524=,tag:2BKIrpkL253iILQJA1lj7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
