apiVersion: v1
kind: ConfigMap
metadata:
    name: web-config
    namespace: aitbase-admin
data:
    nginx-my.conf: ENC[AES256_GCM,data:F2y+PxA0oBsulmfK3ohAVXqpAiijRCjOudG2GKaPEX+Dh0BFG1if2HZcSOAliHgdYZBAezSRP4Il6OwsVRCB+SvSmndWq1wCe84DSsrBKfr1ufnOZIfVLXwcTK+x0CtiKOiMGj9Y/s/0EkBEqiDgSAZbxmCcFKUOaDEbLGFOuUTx6y5i4Zy6RHTkY4tAkTqvi3ILbs4BgJsqwV5RXncJDAbA5edpTQ7ayTKqewBpOAdTkTuenn2nxZuDFHfD/ZJpAu43EBdetzdYVvxy7cbYrRM3A8ZpIrn1t2T4+55tKhb0wBrv4EifeVmfBD5uT2kXe16KDD4ZpcEL4nRH6rdJHioVg+ivaNzACYbPhWPMBVeGHmYCqENRZeYgzb89GnT3/wLBJaXiYM/CqU1ApUM7NWBFp5swC7+welxPcjFAQsloGTHnUij9cHXhgDPPFvfecivcGAhTLhry53jB3nR01QzHnYfCRmGgdggZcgsXvZXkn+k6zZ2Nomk9XYENX/Fzkkrcft9qzcGU7ZIjatz9CuBmdXxBESooFC6F65hhlQ3d5msQXvMRQCofo0G+SEhH4hDqBj22X2SMa1DKg54fQfOl+gH2W2tpQ1Hya8lXAyn8w9+0mThC3F2w7dcI/R5I2hI58LjgFjHvcsUIbGRFJiXbMvAOxFg+XxrfweCCacmyXndoZ9254MCsrtufCVASPy7VklJN4fidJ3WbL/qWclFm6fLbmq7g4dMyNx9sQBKJ0+/HnWZDczrdNLjHNXiVW/ZlEqp5LWyc198hNyZJx69qdC+y+9gkpoTM8H1mKFRyB8B60Gv9Lot+2ADuVXGtYkvcS+WmXm41UqB/Og/4Z7bU/DIq/8RdjR11qmh7PaSegu1NGZJV63QH/2eB6cVnN/w+U7MgIzwCOrASNo/FCbu8XA7UtPLuBjFHfJlqnKR57bWqmdwahoUo03y8og0aq9M5LnyfuQyyuK4GH87onZeoUMnEC6yR0gTg3oKB0wQKpoKRIQu7AdnESIBhpx49YqDHFJfnbWET0sI2ITI29lV2gNy25rk9jtp+0Av+p/U0ASpJWsiBeyKo3oVyzExpZjOXZAZkw8VYtSWfFKmLEamNtmdPXPt0DdozZO1so8DZDXN+puvzeF/1vEhnA6E=,iv:4kGEbubfyuP42BPGlo1m8UUQ88d3X/rkAtNWie/Jngc=,tag:H/IcV3JTvnZzf2qPeVjq9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVTlhclpybCtOVHJYRk9T
            VE45MGRlUGp4Qkp4TThDc0E5V2lQejhQYlhRCk5tamJUUXk5WFQvclA5em5vcjB6
            L095dDNFOEZ3T1lNdml6Zmo5SmpONWsKLS0tIEdMV215c0dOakNza3FyQTVtV0Vx
            SUljb3R5aUlPQXJsWWN5VnIya0VHNmsKSLXJT8KVYCMvNwVDARxaKr4KZANHUqPW
            55CED1NP9KR0GTvVf5jbsLMXgRK4ikavWxXQuEKqDUVv2iYy8gINAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-24T05:07:54Z"
    mac: ENC[AES256_GCM,data:c2ifTouZtHNuELgmEmNQPkAcy5/J1dG0KLPCOkeB3g8olT/vl6SMX9b8r8iz3Tb2c7yCPtyKlkyYa6jkUXu3xD2vJVB+GJWQ6grkaXd8FwllbIXxTjZnL12LXKbJxaBqZvpFFb0Ulfh2tXFbQj0qt8Lhq3A8y3OHuaCUXCeFiUc=,iv:StNHaqECyFiLOJV4Ay1Gbykuq6PJ7zju7bByoC1K0P8=,tag:UK1KdEbvFFPTxafSsZdrLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
