# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: team-edition-mysql-credentials
    namespace: mattermost
stringData:
    mysqlRootPassword: ENC[AES256_GCM,data:NCfbnHOqERAXQLqIUfU=,iv:IeUS7NX+Ho1zhZt/02ZlYMmr1C8JDVhwUO8LtNYwdf0=,tag:6YSBIe6aE/IVt2g/+UeRxQ==,type:str]
    mysqlPassword: ENC[AES256_GCM,data:c09iENMqEs6Kf7CWEEU=,iv:nb+eU4np8Ysg4hloHdUfhCVxdl7JBPWT5ystnWQUlQY=,tag:idVmq9/ulvXd8BHgM43k3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ejFFSnJBMzkyYVNtUVBF
            dWt4VTMrN1l3VnRWRFhyYjBrWk1XTTNmRDBRClowSVVwaXY1bnFOSjA0T1ZSOEZM
            bW4va0xKNzVMRG9QdXhxQW1oajJaRk0KLS0tIHRDeUM1RmU5aWdWcTRwQXF0R3dh
            dHRITE9DdUt5NjRkaEdOcStudlo2aG8KBfgaIvLByCCLIht1dH95y0UOLZKKwWFs
            DJViJOK+koa8OK0oiuY5Bnw0tIVfsw4ywK2QgiMVYR5ni+y19TBMtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-27T02:04:32Z"
    mac: ENC[AES256_GCM,data:cTcPWLWMgr4QzpA5AlRB/HwwTm9ktz0SfA01pbB5ieiWHxXh1ZGJo5mZEWlTgWffhK1gO1XZjiyH0a2L7sBG84zRFlJhCN5xjbxA8St5+AWcirks8eMGf82t+GwOjKUG97Ckvl+FE/898VwN8UvYEaNrVcp4tyw9yhm2cszB+Nw=,iv:g/f+gCdde83wrdXHvw+Zx/HZ318sVMAjMflVhVP84lU=,tag:ExO+a0om1BKnCbwoOd/9WA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
