---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: windmill-server
  namespace: windmill
spec:
  interval: 15m
  chart:
    spec:
      chart: windmill
      version: 2.0.6
      sourceRef:
        kind: HelmRepository
        name: windmill
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    windmill:
      tag: "main"
      image: "aitbase/windmill-puppeteer"
      databaseUrlSecretName: app-secrets
      baseDomain: &host "windmill.aitbase.com"
      baseProtocol: https
      workerGroups:
        # workers configuration
        # The default worker group
        - name: "default"
          replicas: 3
          # -- Annotations to apply to the pods
          annotations: {}

          # -- Node selector to use for scheduling the pods
          nodeSelector: {}

          # -- Tolerations to apply to the pods
          tolerations: []

          # -- Affinity rules to apply to the pods
          affinity: {}

          # -- Resource limits and requests for the pods
          resources:
            requests:
              memory: "1028Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"

          # -- Extra environment variables to apply to the pods
          extraEnv: []

        - name: "native"
          replicas: 4
          # -- Annotations to apply to the pods
          annotations: {}

          # -- Node selector to use for scheduling the pods
          nodeSelector: {}

          # -- Tolerations to apply to the pods
          tolerations: []

          # -- Affinity rules to apply to the pods
          affinity: {}

          # -- Resource limits and requests for the pods
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

          # -- Extra environment variables to apply to the pods
          extraEnv: []
    ingress:
      # -- enable/disable included ingress resource
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
      # -- TLS config for the ingress resource. Useful when using cert-manager and nginx-ingress
      tls:
        - hosts:
            - *host
          secretName: "windmill-server-tls"
