---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: windmill-server
  namespace: windmill
spec:
  interval: 15m
  chart:
    spec:
      chart: windmill
      version: 2.0.6
      sourceRef:
        kind: HelmRepository
        name: windmill
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    windmill:
      databaseUrlSecretName: app-secrets
      baseDomain: &host "windmill.aitbase.com"
      baseProtocol: https
    ingress:
      # -- enable/disable included ingress resource
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
      # -- TLS config for the ingress resource. Useful when using cert-manager and nginx-ingress
      tls:
        - hosts:
            - *host
          secretName: "windmill-server-tls"
