# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:QY25wL5GiyhoMNpOrXtBjD9of4q7SyW2WJ/nYOEyIvgaP5FdYBgmJQ==,iv:lxSeS2VjF2NAV2EH/eMJrTc/uDRbWL97PPFnDjAGDgE=,tag:ki6QMZDxf86ys2eATo4x6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldmhhMVY4M3gxMHlKa2RP
            N1NEUitMcEM5cDlpeVpndE5CeFEwNzJ2cG5vCmFqaFR3bGROdThMWTI5dlpoeHRM
            V0FEVzZJTEQ2MGJKL2t2TENiMUpETG8KLS0tIDVHRkdFSHo1QmViZ3M1RCtYelht
            S0YzWHdBNXhMeHgwb3djZnFkeGpYL00KX8S0ZFA5sA3jekTUCZQuy3I2R6oDhftN
            Kf4UwO/waoMRpu209HcsDsiqGlTKEpM5Zn3NVHpaKZRpF0FaIPD7Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T04:05:16Z"
    mac: ENC[AES256_GCM,data:2sl8f9TlQxwOeoduaMNnQABupEsJAxYKwoGrpL4bFznPE6criJhuY3y5/4iLk2vp8CjHM3fsO2E5Wtt3jspRkwLNHCjezD/jsO0Ku7dw7rSF8wAetn7j0SxMnMrkta3iDS8hsUSDLv5cypaO/sWQgjz6LNk7tYsjSrL2EmsGO00=,iv:Fzw4Ioesm9Mm1vwCEkQbmcn76ydJxCf4ZFq2/pZM+dE=,tag:9TPfaA8FUN55oNSGDBtPWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
