# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+Kr5jZTk/y9kQ5QwzIrhqrCDI06z4qJSAznWqwgNyrUToJ0vnHVnVw==,iv:qUkXep0VZSzgQHtT8oqgg5YCPC0fZEgA1szYb1NRir0=,tag:NOuTa71Lc6g9de1ZvCdVxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eVFaUWxxNXJ2czNaNGNO
            dkFJVk94NG9Qem84YUZYeDgwbTRvN0RaaUVjClVYbWxscEl1REE3TkloUHlvMjBz
            bUJ2ditlRVZMTDFJQlhqbkJZdXNKVkUKLS0tIDNCcFF0djFBajRpbkdFMldScEo3
            Y2tBWmpLVS9JM3hnb1A4MWE4UFFHSTgKMDPxRezNBgIi81ymJWCheTkEggefP3jv
            99owNyMuX/HbRUoyKA3obDpL4gEckPrSHdQ4DM63NsSbEBYk/IO3jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T03:28:41Z"
    mac: ENC[AES256_GCM,data:6Vlkju7ndUVdQyisngVAS9QjXjpOMboUhj0RKqPkmhjYqQcvQzxzx9XfqQ+Vr0l7RBu1m7h3OuWdYj4jf5e8QPmceFEI0jOAeRXa3x01f9E0NFl1v9LhFpQle6bLdvrIEyKbohKX/TtxeiqQhq4wFhenyXWvuIoAhFnWEAOBs+4=,iv:JNXOv/W+4k1XgQ37dCRcVE07AwHg15r0UR271gwmpOE=,tag:2aQOtlnh2mWB/9rx6ky7Cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
