---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nexopos-db
  namespace: nexopos
spec:
  interval: 15m
  chart:
    spec:
      chart: mysql
      version: 9.4.9
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: bitnami/mysql
      tag: 5.7.41
    auth:
      database: vietwings_nexopos
      username: vietwings_nexopos
      existingSecret: db-secrets
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 20Gi
