# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: netmaker-credentials
    namespace: networking
stringData:
    postgresRepmgrPassword: ENC[AES256_GCM,data:CZXcvJgaVImk6g==,iv:UEjUVVc5fiRkKpjFbMm7GcmE6WemarjCKHsQ63At3XQ=,tag:jWDSsAmZU14zL23K74tDBA==,type:str]
    postgresAdminPassword: ENC[AES256_GCM,data:MtF5dMRejcLPsA==,iv:ATmGb6Gh6ODu1uchqpzmjjZfWPkp/47WxZJnioX4lTw=,tag:hB4z+QRBropXfN1lyyYz5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ejFFSnJBMzkyYVNtUVBF
            dWt4VTMrN1l3VnRWRFhyYjBrWk1XTTNmRDBRClowSVVwaXY1bnFOSjA0T1ZSOEZM
            bW4va0xKNzVMRG9QdXhxQW1oajJaRk0KLS0tIHRDeUM1RmU5aWdWcTRwQXF0R3dh
            dHRITE9DdUt5NjRkaEdOcStudlo2aG8KBfgaIvLByCCLIht1dH95y0UOLZKKwWFs
            DJViJOK+koa8OK0oiuY5Bnw0tIVfsw4ywK2QgiMVYR5ni+y19TBMtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-17T08:06:38Z"
    mac: ENC[AES256_GCM,data:PDNhJbNbo32V9uZ9D35Gb4/FD8rJbyiNmSe3Gyjncs/RRxnTw+z57a4Hqeb3K6QXh8YV9Z58BJo3l643RroYpVtIx1hh69DOqKGgSvVLJQVYSglobSL4rARgCDT7ezjGuCuIkYEChEfEFKvovEC8m0WTaQUxp4YcCX3ZVbUyAnc=,iv:DBGc7jqdrLS6D9iBIfQ5vVaSy7OOzaKANciNBiV/OPU=,tag:7CVUW3otjfDFTO7vJ0GnxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
