---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mosquitto
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: mosquitto
      version: 4.8.2
      sourceRef:
        kind: HelmRepository
        name: imtoanle
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    service:
      type: NodePort
      main:
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
    persistence:
      # -- Configure a persistent volume to place mosquitto data in.
      # When enabled, this enables `persistence` and `persistence_location` in the mosquitto config.
      # @default -- See values.yaml
      data:
        enabled: true
        mountPath: /mosquitto/data
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 2Gi
      # -- Configure a persistent volume to place *.conf mosquitto-config-files in.
      # When enabled, this gets set as `include_dir` in the mosquitto config.
      # @default -- See values.yaml
      configinc:
        enabled: true
        mountPath: /mosquitto/configinc
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
