---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder-server
  namespace: coder
spec:
  interval: 15m
  chart:
    spec:
      chart: coder
      version: 0.14.3
      sourceRef:
        kind: HelmRepository
        name: coder-v2
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    coder:
      env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              # You'll need to create a secret called coder-db-url with your
              # Postgres connection URL like:
              # postgres://coder:password@postgres:5432/coder?sslmode=disable
              name: coder-db-url
              key: url

        # (Optional) For production deployments the access URL should be set.
        # If you're just trying Coder, access the dashboard via the service IP.
        - name: CODER_ACCESS_URL
          value: "https://coder.fat-space.com"
      ingress:
        enable: true
        className: 'nginx'
        host: "coder.${SECRET_DOMAIN}"
        wildcardHost: "*.coder.fat-space.com"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        tls:
          enable: true
          secretName: coder-tls
          wildcardSecretName: wildcard-coder-tls
