# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: db-secrets
    namespace: chatwoot
stringData:
    password: ENC[AES256_GCM,data:JTfLqonTT+2t3csIztCm2w==,iv:0K6jkjiTzdwXrJt5rHgjRnPWBOU1BOJD/4Y7g3q2hXA=,tag:593aB+ADfZttEKGy/pk1Vw==,type:str]
    replication-password: ENC[AES256_GCM,data:xE1a2LtwZqIPNqp8FjHvng==,iv:20cYR2O6Fu6dsTIjTCr1ldyRCE7/nT3FbMMEa4QiTGU=,tag:1liuJc/kH5dwmakyvHWIPg==,type:str]
    postgres-password: ENC[AES256_GCM,data:pK/98si1yo0fJ6bIR/l8Rg==,iv:iU4Kii64csjU2CHHYgsRdiJsvU/m5wne5wYCUbKzmwU=,tag:Zt3BUh/ARvOobCwW2t+FlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nd65hrj4sk76qrmttmmlc4uuk4nlg6n6r9y43r4t3q2032eedg7qn95ynh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ejFFSnJBMzkyYVNtUVBF
            dWt4VTMrN1l3VnRWRFhyYjBrWk1XTTNmRDBRClowSVVwaXY1bnFOSjA0T1ZSOEZM
            bW4va0xKNzVMRG9QdXhxQW1oajJaRk0KLS0tIHRDeUM1RmU5aWdWcTRwQXF0R3dh
            dHRITE9DdUt5NjRkaEdOcStudlo2aG8KBfgaIvLByCCLIht1dH95y0UOLZKKwWFs
            DJViJOK+koa8OK0oiuY5Bnw0tIVfsw4ywK2QgiMVYR5ni+y19TBMtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-07T04:41:46Z"
    mac: ENC[AES256_GCM,data:D7U49QpddMqGOeXXgDtdmgkRD4bapV+/ONpZ8kIa5cHuDl4EeqZYB6Nv0GQo3Tk2DYVIoaJKWXuHrxgzG6IussClAhzmcJVhkqonTDJK1IhpDB2DPHn98C3xhe/8YheZLgqIEbASJveYq75iux893d77gOOziZaf6DV7SL0d5PM=,iv:01PkT0LahGsX/lQUb2D2R5yNA4wm/yfSnU9Mxdc1tRk=,tag:QJ6KOoFCLlsE/x2gOvEwGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
